apiVersion: apps/v1
kind: Deployment
metadata:
  name: salimnextdev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salimnextdev
  template:
    metadata:
      labels:
        app: salimnextdev
    spec:
      containers:
      - name: salimnextdev
        image: 467808956895.dkr.ecr.us-west-2.amazonaws.com/salimdevsecops
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: salimnextdev
    k8s-app: salimnextdev
  name: salimnextdev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: salimnextdev
